In [ ]:
#Hide warnings
from silence_tensorflow import silence_tensorflow
silence_tensorflow()
import tensorflow as tf

In [ ]:
from tensorflow import keras
accumulatorc = keras.models.load_model('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/weights/accumulator.h5')
coolerc = keras.models.load_model('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/weights/cooler.h5')
stablec= keras.models.load_model('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/weights/stable.h5')
valvec = keras.models.load_model('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/weights/valve.h5')
leakagec = keras.models.load_model('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/weights/leakage.h5')
rulc = keras.models.load_model('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/weights/rul.h5')

In [ ]:
# load the dataset 
import pandas as pd
import numpy as np

dt = pd.read_excel('/content/drive/MyDrive/Pump Predictive Maintenance/Condition Hydraulic Pump/condition Hydraulic.xlsx')

In [ ]:
df = pd.DataFrame(dt, columns=['PS1','PS3', 'PS4', 'PS5', 'FS1', 'FS2', 'TS1', 'P1', 'VS1', 'CE1', 'CP1', 'SE1', 'leakage', 'valve', 'cooler', 'accumulator', 'rul', 'label1'])
df.sample(10)

PS1       PS3        PS4  ...  accumulator        rul  label1
2114  160.671200  1.949312  10.116157  ...           90   0.166667       1
1041  158.755557  1.787245   0.000000  ...          130   0.000000       1
971   157.900827  1.715422   0.000000  ...          130   0.000000       1
543   172.784225  1.084655   0.000000  ...          100   0.000000       1
1511  160.998580  2.013957   0.710880  ...           90  27.333333       0
1152  158.453738  1.759557   0.000000  ...          115   0.000000       1
1984  160.730637  1.935376  10.051590  ...          100   0.000000       1
599   156.148142  1.722848   0.000000  ...           90   1.833333       0
670   172.878865  1.095611   0.000513  ...           90   0.000000       1
1146  158.527948  1.763424   0.000000  ...          115   0.000000       1

[10 rows x 18 columns]

In [ ]:
print(df['leakage'].unique())
print(df['cooler'].unique())
print(df['accumulator'].unique())
print(df['valve'].unique())
print(df['label1'].unique())

[0 2 1]
[  3  20 100]
[130 115 100  90]
[100  73  80  90]
[0 1]


In [ ]:
X = df.iloc[:, :12]
y = df.iloc[:, 15]

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42, stratify=y)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
df.sample(10)

PS1       PS3        PS4  ...  accumulator        rul  label1
1879  160.565385  1.948675  10.098277  ...          115   0.000000       1
1806  160.894388  1.999104  10.071829  ...          115   0.333333       1
838   158.277698  1.799744   0.000000  ...           90  17.500000       0
160   156.951137  1.738583   0.000000  ...          130   8.500000       0
921   158.406957  1.777062   0.000000  ...           90   3.666667       0
855   158.308372  1.792338   0.000000  ...           90  14.666667       0
1639  161.061293  2.002360   2.583576  ...           90   6.000000       0
1878  160.610177  1.938668  10.093895  ...          115   0.000000       1
2037  161.097873  2.000081  10.076048  ...          100   0.000000       1
757   157.830742  1.762823   0.000000  ...           90  31.000000       0

[10 rows x 18 columns]

In [ ]:
a=np.array([[160.610177,	1.938668,	10.093895,	9.863730,	6.520082,	10.177712,	36.187783,	2553.700133,	0.539883,	47.163433,	2.165833,	57.008067]])
ac=sc.transform(a)

In [ ]:
failure = np.argmax(stablec.predict(ac), axis=-1)
stab=['stable', 'failure']
print("The Hydraulic pump is {}".format(stab[failure[0]]))
cooler = np.argmax(coolerc.predict(ac), axis=-1)
cool=['3(close to failure)', '20(reduced efficiency)', '100(full efficiency)']
print("Condition of cooler is {}".format(cool[cooler[0]]))
leakage = np.argmax(leakagec.predict(ac), axis=-1)
leak =['0 (No leak)', '1 (weak leak)','2 (severe leak)']
print("Condition of Internal Pump Leakage is {}".format(leak[leakage[0]]))
valve = np.argmax(valvec.predict(ac), axis=-1)
val =['73 (close to total failure)', '80 (Severe lag)', '90 (small lag)', '100 (optimal switching behaviour)']
print("Condition of Valve is {}".format(val[valve[0]]))
accumulator = np.argmax(accumulatorc.predict(ac), axis=-1)
accu= ['90 (close to total failure)', '100 (severely reduced pressure)', '115 (slightly reduced pressure)', '130 (optimal pressure)']
print("Condition of Hydraulic accumulator is {}".format(accu[accumulator[0]]))
rul=rulc.predict([ac])
print("Remaining useful life before failure is {} minutes".format(max(0, rul[0])))

The Hydraulic pump is failure
Condition of cooler is 100(full efficiency)
Condition of Internal Pump Leakage is 1 (weak leak)
Condition of Valve is 100 (optimal switching behaviour)
Condition of Hydraulic accumulator is 130 (optimal pressure)
Remaining useful life before failure is [0.01968958] minutes
